services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: comp3133-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

 


