services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: comp3133-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: comp3133-frontend
    ports:
      - "4200:4200"
    restart: unless-stopped

    

 


